name: Build Openwrt

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install depends
      run: |
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint

    - name: Clone source code
      run: |
        git clone https://github.com/openwrt/openwrt.git

    - name: Customize
      run: |
        mv config openwrt/.config
        cd openwrt
        git config --global user.email "4585006@gmail.com"
        git config --global user.name "w01230"
        echo "src-git extra https://github.com/w01230/openwrt-extra.git" >> feeds.conf.default
        ./scripts/feeds update -a
        git am feeds/extra/patch/0001-openwrt-customize.patch
        cd feeds/luci
        git am ../extra/patch/0001-luci-customize.patch
        cd ../../
        ./scripts/feeds install -a
        make defconfig

    - name: Build
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: OpenWrt firmware
        path: openwrt/bin/targets


